//
//  HomeInteractor.swift
//  ArchitecturesUIKit
//
//  Created by Frédéric Helfer on 14/02/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeBusinessLogic
{
    func fetchData() async
}

protocol HomeDataStore
{
    //var name: String { get set }
}

class HomeInteractor: HomeBusinessLogic, HomeDataStore
{
    var presenter: HomePresentationLogic?
    var worker: HomeWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func fetchData() async {
        worker = HomeWorker()
        do {
            guard let allPersons = try await worker?.fetchPersons() else { return }
            presenter?.presentSomething(response: Home.Something.Response(allPersons: allPersons))
        } catch {
            presenter?.presentError(response: Home.Something.ViewError(error: error))
        }
    }
}
