//
//  HomeRouter.swift
//  ArchitecturesUIKit
//
//  Created by Frédéric Helfer on 14/02/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol HomeRoutingLogic
{
    func routeToLogin()
}

protocol HomeDataPassing
{
    var dataStore: HomeDataStore? { get }
}

class HomeRouter: NSObject, HomeRoutingLogic, HomeDataPassing
{
    weak var viewController: HomeViewController?
    var dataStore: HomeDataStore?
    
    // MARK: - Routing
    
    func routeToLogin() {
        viewController?.navigationController?.popViewController(animated: true)
    }

    
    // MARK: - Navigation
    
    func navigateToPush(source: LoginViewController, destination: UIViewController)
    {
        destination.modalPresentationStyle = .fullScreen
        source.navigationController?.pushViewController(destination, animated: true)
    }
    
    func navigateToModal(source: LoginViewController, destination: UIViewController)
    {
        destination.modalPresentationStyle = .fullScreen
        source.navigationController?.present(destination, animated: true)
    }
    
    // MARK: Passing data
    
    //func passDataToSomewhere(source: HomeDataStore, destination: inout SomewhereDataStore)
    //{
    //  destination.name = source.name
    //}
}
