//
//  HomePresenter.swift
//  ArchitecturesUIKit
//
//  Created by Frédéric Helfer on 14/02/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomePresentationLogic
{
    func presentSomething(response: Home.Something.Response)
    func presentError(response: Home.Something.ViewError)
}

class HomePresenter: HomePresentationLogic
{
    weak var viewController: HomeDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: Home.Something.Response) {
        let viewModel = Home.Something.ViewModel(allPersons: response.allPersons)
        viewController?.displaySomething(viewModel: viewModel)
    }
    
    func presentError(response: Home.Something.ViewError) {
        viewController?.displayError(error: response)
    }
}
