//
//  LoginInteractor.swift
//  ArchitecturesUIKit
//
//  Created by Frédéric Helfer on 14/02/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginBusinessLogic
{
    func doSomething(request: Login.Something.Request)
}

protocol LoginDataStore
{
    //var name: String { get set }
}

class LoginInteractor: LoginBusinessLogic, LoginDataStore
{
    var presenter: LoginPresentationLogic?
    var worker: LoginWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func doSomething(request: Login.Something.Request)
    {
        worker = LoginWorker()
        worker?.login(user: request.credentials, completionHandler: { [weak self] result in
            switch result {
            case .success(_):
                let response = Login.Something.Response()
                self?.presenter?.presentSomething(response: response)
            case .failure(let error):
                let viewError = Login.Something.ViewError(error: error)
                self?.presenter?.presentError(response: viewError)
            }
        })
    }
}
