//
//  LoginViewController.swift
//  ArchitecturesUIKit
//
//  Created by Frédéric Helfer on 14/02/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginDisplayLogic: AnyObject
{
    func displaySomething(viewModel: Login.Something.ViewModel)
    func displayError(error: Login.Something.ViewError)
}

class LoginViewController: UIViewController, LoginDisplayLogic
{
    var interactor: LoginBusinessLogic?
    var router: (NSObjectProtocol & LoginRoutingLogic & LoginDataPassing)?
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
    {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder)
    {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup()
    {
        let viewController = self
        let interactor = LoginInteractor()
        let presenter = LoginPresenter()
        let router = LoginRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?)
    {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: View lifecycle
    
    override func loadView() {
        super.loadView()
        view = loginView
    }
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
        self.hideKeyboardWhenTappedAround()
    }
    
    // MARK: - Do something
    lazy var loginView: LoginView = {
        let view = LoginView()
        
        view.onLoginTap = { [weak self] user in
            self?.loginTap(user: user)
        }
        
        view.onRegisterTap = { [weak self] in
            self?.registerTap()
        }
        
        return view
    }()
    
    // MARK: - Actions
    func loginTap(user: Credentials) {
        let request = Login.Something.Request(credentials: user)
        interactor?.doSomething(request: request)
    }
    
    func registerTap() {
        router?.routeToRegister()
    }
    
    // MARK: - display
    func displaySomething(viewModel: Login.Something.ViewModel)
    {
        router?.routeToHome()
    }
    
    func displayError(error: Login.Something.ViewError) {
        presentAlert(withTitle: "Erro", message: error.error.localizedDescription)
    }
}
