//
//  RegisterRouter.swift
//  ArchitecturesUIKit
//
//  Created by Frédéric Helfer on 14/02/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol RegisterRoutingLogic
{
    func routeToHome()
}

protocol RegisterDataPassing
{
    var dataStore: RegisterDataStore? { get }
}

class RegisterRouter: NSObject, RegisterRoutingLogic, RegisterDataPassing
{
    weak var viewController: RegisterViewController?
    var dataStore: RegisterDataStore?
    
    // MARK: Routing
    func routeToHome() {
        let destinationVC = HomeViewController()
        navigateToPush(source: viewController!, destination: destinationVC)
    }
    
    
    // MARK: Navigation
    
    func navigateToPush(source: RegisterViewController, destination: UIViewController)
    {
        destination.modalPresentationStyle = .fullScreen
        source.navigationController?.pushViewController(destination, animated: true)
    }
    
    func navigateToModal(source: RegisterViewController, destination: UIViewController)
    {
        destination.modalPresentationStyle = .fullScreen
        source.navigationController?.present(destination, animated: true)
    }
    
    // MARK: Passing data
    
    //func passDataToSomewhere(source: RegisterDataStore, destination: inout SomewhereDataStore)
    //{
    //  destination.name = source.name
    //}
}
