//
//  RegisterInteractor.swift
//  ArchitecturesUIKit
//
//  Created by Frédéric Helfer on 14/02/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RegisterBusinessLogic
{
    func doSomething(request: Register.Something.Request)
}

protocol RegisterDataStore
{
    //var name: String { get set }
}

class RegisterInteractor: RegisterBusinessLogic, RegisterDataStore
{
    var presenter: RegisterPresentationLogic?
    var worker: RegisterWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func doSomething(request: Register.Something.Request)
    {
        worker = RegisterWorker()
        worker?.register(user: request.user, completionHandler: { [weak self] result in
            switch result {
            case .success(_):
                let response = Register.Something.Response()
                self?.presenter?.presentHomeView(response: response)
            case .failure(let error):
                let error = Register.Something.ViewError(error: error)
                self?.presenter?.presentError(response: error)
            }
        })
    }
}
